export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const LOGOUT = "LOGOUT";

export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const ERROR_FETCH_DATA = "ERROR_FETCH_DATA";

export const SERVER_ERROR = "SERVER_ERROR";

export const FETCH_ALL_USER_DATA = "FETCH_ALL_USER_DATA";
export const ERROR_FETCH_ALL_DATA = "ERROR_FETCH_ALL_DATA";
export const ADD_DESIGNATIONS = "ADD_DESIGNATIONS";
export const SET_DATA_ERROR = "SET_DATA_ERROR";

export const GET_TASKS = "GET_TASKS";
export const GET_LEAVES = "GET_LEAVES";

export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_LEAVE = "FETCH_LEAVE";

export const APPROVE_LEAVE = "APPROVE_LEAVE";
export const REJECT_LEAVE = "REJECT_LEAVE";
export const FORWARD_LEAVE = "FORWARD_LEAVE";

export const FETCH_ALL_SALARY_DETAILS = "FETCH_ALL_SALARY_DETAILS";
export const FETCH_EMPLOYEE_SALARY_DETAILS = "FETCH_EMPLOYEE_SALARY_DETAILS";

export const FETCH_EMPLOYEE_GRADE_HISTORY = "FETCH_EMPLOYEE_GRADE_HISTORY";

export const FETCH_EMPLOYEE_REPORT = "FETCH_EMPLOYEE_REPORT";
export const FETCH_TASK_REPORT = "FETCH_TASK_REPORT";
export const FETCH_SALARY_REPORT = "FETCH_SALARY_REPORT";
export const FETCH_LEAVE_REPORT = "FETCH_LEAVE_REPORT";

export const CLEAN_STUFF = "CLEAN_STUFF";
